spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://139.196.242.21:3306/gulimall-ums
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000
