spring:
  cloud:
    nacos:
      server-addr: 139.196.242.21:8848
  alicloud:
    access-key: LTAI5tKep7GH995eykpvvUGN
    secret-key: oaf8CmhacQViCDI11KZ2PdTqpJuesq
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com

  application:
    name: precisehelp-third-party
server:
  port: 30000
